In [1]:
import numpy as np
import pandas as pd

In [2]:
import gensim

Pretrained model

In [3]:
import gensim.downloader as api
glove_model= api.load('glove-wiki-gigaword-300')

[=================================================-] 99.8% 375.2/376.1MB downloaded


In [4]:
# Vector representation of word
glove_model['beautiful']

array([-2.3852e-01, -3.3704e-01, -2.6531e-01, -3.4693e-01, -1.2875e-01,
        1.0698e-01, -2.4669e-02,  2.6829e-02, -1.0024e-01, -9.1494e-01,
        4.8989e-01, -1.0362e-01, -2.4535e-01,  5.7003e-01, -3.5189e-02,
       -3.7690e-01, -6.9177e-02, -2.5942e-01,  2.2511e-01,  5.1855e-01,
       -3.9326e-01,  1.2665e+00, -4.4396e-01,  7.6827e-01, -1.0909e-02,
       -2.4237e-01, -1.0275e-01, -4.9712e-01, -8.0183e-02,  4.0611e-01,
        2.1275e-01,  6.5182e-01, -1.1487e+00,  4.6080e-03, -6.8265e-01,
        9.6941e-01, -7.6194e-02, -4.1590e-01, -2.7069e-01, -5.3364e-02,
       -7.9631e-02, -2.6670e-01, -2.1544e-02,  2.2392e-01,  5.5741e-02,
        8.4611e-02,  8.6011e-01,  4.8927e-01,  4.7428e-01, -2.4446e-01,
       -2.1553e-01,  1.4370e-01,  5.0683e-01, -5.8435e-01, -5.6243e-01,
       -6.3757e-02, -2.2861e-01, -6.9374e-02,  5.6618e-01, -8.7813e-02,
       -2.1272e-01, -1.6319e-01,  3.3545e-01,  1.3707e-01, -1.1920e-03,
        9.7461e-02,  3.2382e-01, -2.2693e-01, -1.7767e-01,  4.01

In [5]:
glove_model['beautiful'].shape

(300,)

In [6]:
glove_model.most_similar('son')

[('father', 0.8562743663787842),
 ('brother', 0.8323165774345398),
 ('daughter', 0.7956427335739136),
 ('grandson', 0.7869758605957031),
 ('eldest', 0.7859813570976257),
 ('nephew', 0.7693369388580322),
 ('sons', 0.7442554235458374),
 ('cousin', 0.7059624791145325),
 ('grandfather', 0.699710488319397),
 ('uncle', 0.6803406476974487)]

In [7]:
# queen-girl=boy=king
glove_model.most_similar(positive= ['boy', 'queen'], negative= ['girl'], topn= 1)

[('king', 0.6770139932632446)]

Build own model

In [8]:
!pip install flair

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 373.1/373.1 kB 28.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 70.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 26.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 35.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 69.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 17.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.5/788.5 kB 64.8 MB/s eta 0:00:0

In [9]:
from flair.data import Sentence
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from scipy.spatial import distance

In [10]:
glove_embeddings= WordEmbeddings('glove')

2023-05-04 16:07:55,291 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpa4finqp5


100%|██████████| 153M/153M [00:13<00:00, 11.5MB/s]

2023-05-04 16:08:09,922 copying /tmp/tmpa4finqp5 to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2023-05-04 16:08:10,099 removing temp file /tmp/tmpa4finqp5
2023-05-04 16:08:10,842 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpz9iiok5t


100%|██████████| 20.5M/20.5M [00:03<00:00, 6.49MB/s]

2023-05-04 16:08:14,854 copying /tmp/tmpz9iiok5t to cache at /root/.flair/embeddings/glove.gensim
2023-05-04 16:08:14,874 removing temp file /tmp/tmpz9iiok5t


In [11]:
sentence1= Sentence('apple released iphone 14 in 2023')

In [12]:
glove_embeddings.embed(sentence1)

[Sentence[6]: "apple released iphone 14 in 2023"]

In [13]:
for token in sentence1:
  print(token)
  print(token.embedding)
  print("\n")

Token[0]: "apple"
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.03

In [14]:
sentence1[0]

Token[0]: "apple"

In [15]:
sentence1[0].embedding.shape

torch.Size([100])

In [16]:
sentence2= Sentence('an apple is good for health')

In [17]:
glove_embeddings.embed(sentence2)

[Sentence[6]: "an apple is good for health"]

In [18]:
for token in sentence2:
  print(token)
  print(token.embedding)
  print("\n")

Token[0]: "an"
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,

Glove distance between same word in different sentence and has different meaning

In [19]:
glove_distance= distance.euclidean(sentence1[0].embedding.detach().cpu().numpy(),
                                   sentence2[1].embedding.detach().cpu().numpy())

In [20]:
print("Distance between apple embedding for GLove={}".format(glove_distance))

Distance between apple embedding for GLove=0.0


In [21]:
sentence3= Sentence('python is good for data scientist')
sentence4= Sentence('tableau is good for visualization')

In [22]:
glove_embeddings.embed(sentence3)
glove_embeddings.embed(sentence4)

[Sentence[5]: "tableau is good for visualization"]

In [23]:
glove_distance= distance.euclidean(sentence1[0].embedding.detach().cpu().numpy(),
                                   sentence2[0].embedding.detach().cpu().numpy())

In [24]:
print("Distance between python and tableau embedding for GLove={}".format(glove_distance))

Distance between python and tableau embedding for GLove=7.483118057250977


Real time dataset- Happy moment dataset

In [25]:
import numpy as np
import pandas as pd

In [26]:
data= pd.read_csv('/content/cleaned_hm.csv')
data.head()

hmid   wid reflection_period  \
0  27673  2053               24h   
1  27674     2               24h   
2  27675  1936               24h   
3  27676   206               24h   
4  27677  6227               24h   

                                         original_hm  \
0  I went on a successful date with someone I fel...   
1  I was happy when my son got 90% marks in his e...   
2       I went to the gym this morning and did yoga.   
3  We had a serious talk with some friends of our...   
4  I went with grandchildren to butterfly display...   

                                          cleaned_hm  modified  num_sentence  \
0  I went on a successful date with someone I fel...      True             1   
1  I was happy when my son got 90% marks in his e...      True             1   
2       I went to the gym this morning and did yoga.      True             1   
3  We had a serious talk with some friends of our...      True             2   
4  I went with grandchildren to butterfly display...      True             1   

  ground_truth_category predicted_category  
0                   NaN          affection  
1                   NaN          affection  
2                   NaN           exercise  
3               bonding            bonding  
4                   NaN          affection

In [28]:
data.columns

Index(['hmid', 'wid', 'reflection_period', 'original_hm', 'cleaned_hm',
       'modified', 'num_sentence', 'ground_truth_category',
       'predicted_category'],
      dtype='object')

In [29]:
data['predicted_category'].value_counts()

affection           34168
achievement         33993
enjoy_the_moment    11144
bonding             10727
leisure              7458
nature               1843
exercise             1202
Name: predicted_category, dtype: int64

In [30]:
data['num_sentence'].value_counts()

1     83711
2      9542
3      3847
4      1624
5       821
6       336
7       183
8       107
10       68
9        61
11       35
13       26
12       21
16       17
18       17
14       14
17       14
19       12
21       10
15        7
23        7
25        7
26        5
24        5
22        4
30        3
31        3
20        3
29        3
27        2
32        2
40        2
37        2
69        1
60        1
34        1
42        1
44        1
48        1
35        1
46        1
51        1
56        1
53        1
58        1
28        1
45        1
Name: num_sentence, dtype: int64

In [32]:
data.shape

(100535, 9)

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100535 entries, 0 to 100534
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype 
---  ------                 --------------   ----- 
 0   hmid                   100535 non-null  int64 
 1   wid                    100535 non-null  int64 
 2   reflection_period      100535 non-null  object
 3   original_hm            100535 non-null  object
 4   cleaned_hm             100535 non-null  object
 5   modified               100535 non-null  bool  
 6   num_sentence           100535 non-null  int64 
 7   ground_truth_category  14125 non-null   object
 8   predicted_category     100535 non-null  object
dtypes: bool(1), int64(3), object(5)
memory usage: 6.2+ MB


In [35]:
# Remove happy moment where more than 10 sentences occurs
mod_data= data.loc[data['num_sentence']<=10]
mod_data['predicted_category'].value_counts()

affection           34020
achievement         33966
enjoy_the_moment    11115
bonding             10700
leisure              7458
nature               1839
exercise             1202
Name: predicted_category, dtype: int64

In [36]:
mod_data.shape

(100300, 9)